### ISSUE TITLE
Why is PHP installed as user 1001 with some random group (e.g. epmd or docker) ?

### ISSUE THREAD

**Issue by HenkPoley** [shivammathur/php-builder#10]
The 'random group' might be the nearest to GID=1001. E.g. for one of my systems epmd GID=116, another system docker GID=1001

**Comment by shivammathur** [comment]
Can you provide a test `Dockerfile` to reproduce the issue?

**Comment by HenkPoley** [comment]
No. I'm not using this on Docker, but Ubuntu on WSL1 & WSL2

Maybe that's the issue (?)

**Comment by shivammathur** [comment]
@HenkPoley 
Should be fixed by https://github.com/shivammathur/php-builder/commit/5e905dd2f0a75f06978ae79a1e38e3aa9eac40b3

Fetch [`install.sh`](https://github.com/shivammathur/php-builder/releases/latest/download/install.sh) and install again.

**Comment by HenkPoley** [comment]
The folders and files are now all(?) owned by root.

**Comment by shivammathur** [comment]
That should be alright, Does it cause any permission issues while running PHP?
