### ISSUE TITLE
`imagick` extension compiles with non-semver version

### ISSUE THREAD

**Issue by boesing** [shivammathur/php-builder#11]
Hey there,

we've added some output to our CI pipeline regarding PHP extensions and their versions.
We do **NOT** have any issues with this as we are not using that version to compare against with `version_compare`. Not sure if this might lead to issues else where.

It actually compiles with `@PACKAGE_VERSION@`:
```
<?= phpversion('imagick'); ?>
```

Not sure if this is fixable or even needs to be addressed. I've just discovered this and wanted to push to this issue tracker.

https://github.com/boesing/typed-arrays/pull/99/checks?check_run_id=3413537719

**Comment by shivammathur** [comment]
@boesing 
Fixed in https://github.com/shivammathur/php-builder/commit/06e94236ee172c0b9b6210f15f7783764f41c83f

**Comment by boesing** [comment]
Wow, you are really amazing. Thanks!
