### ISSUE TITLE
Issue with argon hashing configuration

### ISSUE THREAD

**Issue by GrahamCampbell** [shivammathur/php-builder#2]
I don't have an exact date this broke, but I can say it was working 16 days ago, and not working over the last 4 days. I think there is some issue with the configure build step, only affecting the nightly linux builds (and not Windows), which is causing:

```
ValueError: A thread value other than 1 is not supported by this implementation
```

When the following code is run:

```php
password_hash('password', PASSWORD_ARGON2I, [
    'memory_cost' => 1024,
    'time_cost' => 2,
    'threads' => 2,
]);
```

When I build PHP 8 on my own Debian machine (not using this repo), then I don't see the issue, which is why I think there must be a build configuration issue specifically here.

**Comment by GrahamCampbell** [comment]
I think the issue as simple as this: https://github.com/shivammathur/php-builder/pull/3. I guess PHP didn't used to hard fail until recently, which is why this has gone unnoticed.

**Comment by MHCreations** [comment]
This issue is with PHP 7.4.20 . As of this date (June 2021) this remains in place.
