### ISSUE TITLE
Installation successfully done but php not properly installed

### ISSUE THREAD

**Issue by ZobairQ** [shivammathur/php-builder#5]
After I installed it php 8.0 using your instructions, when I run `php -v`
I get the following error 

`php: symbol lookup error: php: undefined symbol: zip_encryption_method_supported`

**Comment by shivammathur** [comment]
Make sure `libzip-dev` was installed during the installation.
```
sudo apt-get install -y libzip-dev
```

Also provide the output of the following command
```
sudo apt-cache policy libzip-dev
```

**Comment by shivammathur** [comment]
I have removed `--no-upgrade` from the install script. Since you are installing `libzip-dev` in your dockerfile before running `install.sh`, it did not upgrade it to the required version of `libzip-dev`, now it will. So please try again.

**Comment by ZobairQ** [comment]
It is working perfectly thank you alot Shivam!
<img width="2344" alt="billede" src="https://user-images.githubusercontent.com/14279865/98484881-cc766900-2212-11eb-8b4d-2b86db692da4.png">
