### ISSUE TITLE
Require librabbitmq4, libodbc1, libodbcinstq4-1, libmemcached11

### ISSUE THREAD

**Issue by HenkPoley** [shivammathur/php-builder#9]
To run `php8.1 --version` without dynamic library load errors on Ubuntu 18.04.5 LTS I had to install these packages

```shell
sudo apt install librabbitmq4 libodbc1 libodbcinstq4-1 libmemcached11 
```

**Comment by shivammathur** [comment]
@HenkPoley Fixed in https://github.com/shivammathur/php-builder/commit/e796caf93d97b98945f46744658ba9249093b1d6
